### ISSUE TITLE
conda import environment.yml error

### ISSUE THREAD

**Issue by yuanotes** [udacity/deep-learning#101]
When I run `conda env create -f ./environments/dl_env_mac.yml` on Mac, I get error output:

> Using Anaconda API: https://api.anaconda.org
> Fetching package metadata .........
> 
> 
> NoPackagesFoundError: Package missing in current osx-64 channels: 
>   - tornado 4.5 py36_0
> 

When I run `conda search tornado`, it seems that there's no 4.5 version of tornado at all.

**Comment by mcleonard** [comment]
Thanks, I'll fix that

**Comment by mcleonard** [comment]
@yuanotes I'm seeing tornado 4.5 just find from `conda search tornado`. You might need to update conda. try `conda update conda`. Otherwise, I'm not sure. I see the package fine. It has a 2.7, 3.5, and 3.6 version.

**Comment by yuanotes** [comment]
I have upgrade conda from 4.3.14-py36_0 --> 4.3.16-py36_0 and when I search tornado the ouput is:

> ...
> tornado                      2.3                      py26_0  defaults        
>                              2.3                      py27_0  defaults        
>                              2.4.1                    py26_0  defaults        
>                              2.4.1                    py27_0  defaults        
>                              2.4.1                    py33_0  defaults        
>                              3.0.1                    py26_0  defaults        
>                              3.0.1                    py27_0  defaults        
>                              3.0.1                    py33_0  defaults        
>                              3.0.2                    py26_0  defaults        
>                              3.0.2                    py27_0  defaults        
>                              3.0.2                    py33_0  defaults        
>                              3.1                      py26_0  defaults        
>                              3.1                      py27_0  defaults        
>                              3.1                      py33_0  defaults        
>                              3.1.1                    py26_0  defaults        
>                              3.1.1                    py27_0  defaults        
>                              3.1.1                    py33_0  defaults        
>                              3.2.0                    py26_0  defaults        
>                              3.2.0                    py27_0  defaults        
>                              3.2.0                    py33_0  defaults        
>                              3.2.0                    py34_0  defaults        
>                              3.2.1                    py26_0  defaults        
>                              3.2.1                    py27_0  defaults        
>                              3.2.1                    py33_0  defaults        
>                              3.2.1                    py34_0  defaults        
>                              3.2.2                    py26_0  defaults        
>                              3.2.2                    py27_0  defaults        
>                              3.2.2                    py33_0  defaults        
>                              3.2.2                    py34_0  defaults        
>                              4.0.1                    py26_0  defaults        
>                              4.0.1                    py27_0  defaults        
>                              4.0.1                    py33_0  defaults        
>                              4.0.1                    py34_0  defaults        
>                              4.0.2                    py26_0  defaults        
>                              4.0.2                    py27_0  defaults        
>                              4.0.2                    py33_0  defaults        
>                              4.0.2                    py34_0  defaults        
>                              4.1                      py26_0  defaults        
>                              4.1                      py27_0  defaults        
>                              4.1                      py33_0  defaults        
>                              4.1                      py34_0  defaults        
>                              4.2                      py26_0  defaults        
>                              4.2                      py27_0  defaults        
>                              4.2                      py33_0  defaults        
>                              4.2                      py34_0  defaults        
>                              4.2.1                    py26_0  defaults        
>                              4.2.1                    py27_0  defaults        
>                              4.2.1                    py33_0  defaults        
>                              4.2.1                    py34_0  defaults        
>                              4.2.1                    py35_0  defaults        
>                              4.2.1                    py27_1  defaults        
>                              4.2.1                    py34_1  defaults        
>                              4.2.1                    py35_1  defaults        
>                              4.3                      py27_0  defaults        
>                              4.3                      py34_0  defaults        
>                              4.3                      py35_0  defaults        
>                              4.3                      py27_1  defaults        
>                              4.3                      py34_1  defaults        
>                              4.3                      py35_1  defaults        
>                              4.4.1                    py27_0  defaults        
>                              4.4.1                    py34_0  defaults        
>                              4.4.1                    py35_0  defaults        
>                              4.4.2                    py27_0  defaults        
>                              4.4.2                    py34_0  defaults        
>                              4.4.2                    py35_0  defaults        
>                              4.4.2                    py36_0  defaults        
>                              4.5.1                    py27_0  defaults        
>                              4.5.1                    py35_0  defaults        
>                           *  4.5.1                    py36_0  defaults
> ...

I changed the yml file to make tornado version to 4.5.1 to work around this.

**Comment by mcleonard** [comment]
Interesting! Okay, changed the environment files. Thanks!
