### ISSUE TITLE
Where is the face_generation folder?

### ISSUE THREAD

**Issue by mithi** [udacity/deep-learning#115]
It was said to be here. Where is it?

**Comment by Brok-Bucholtz** [comment]
The face generation project isn't current out.  Why are you looking for the folder?

**Comment by reneeichhorn** [comment]
The reviewer introduction is pointing towards here. https://review.udacity.com/#!/rubrics/891/instructions

**Comment by mithi** [comment]
@Brok-Bucholtz , what @reneeichhorn said. thanks!

**Comment by Brok-Bucholtz** [comment]
It's officially not out yet, but you can use this link:
https://github.com/udacity/deep-learning/tree/week_17

**Comment by mithi** [comment]
@Brok-Bucholtz  okay thanks!
