### ISSUE TITLE
the  build_rnn function in Anna_KaRNNa run fail

### ISSUE THREAD

**Issue by zephoon** [udacity/deep-learning#127]
just clone the TensorBoard project and I want to runabout something wrong.

```
//Write out the graph for TensorBoard
model = build_rnn(len(vocab),
                  batch_size=batch_size,
                  num_steps=num_steps,
                  learning_rate=learning_rate,
                  lstm_size=lstm_size,
                  num_layers=num_layers,
                  sampling=sampling,
                  grad_clip=grad_clip
                 )

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    file_writer = tf.summary.FileWriter('./logs/1', sess.graph)
```
the build_rnn run fail with these wrong:
---------------------------------------------------------------------------
```
ValueError                                Traceback (most recent call last)
<ipython-input-63-f61b00ac8e27> in <module>()
      6                   num_layers=num_layers,
      7                   sampling=sampling,
----> 8                   grad_clip=grad_clip,
      9                  )
     10 
```
I don't know what is wrong?

**Comment by llealgt** [comment]
Any solution? in my case it also fails(without modifying the notebook) with this:
Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/weights, but specified shape (1024, 2048) and found shape (595, 2048).

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
