### ISSUE TITLE
Hard coded  'Real Input' in _check_input test method should be display_name

### ISSUE THREAD

**Issue by jg1141** [udacity/deep-learning#136]
On line 34 of [problem_unittests.py](https://github.com/udacity/deep-learning/blob/master/face_generation/problem_unittests.py)
`    _assert_tensor_shape(tensor, shape, 'Real Input')`
should be
`    _assert_tensor_shape(tensor, shape, display_name)`

**Comment by abhiojha8** [comment]
Thanks for the feedback!
