### ISSUE TITLE
Anna_KaRNNa notebook not runnable due to `ValueError`

### ISSUE THREAD

**Issue by dxl0632** [udacity/deep-learning#146]
Error message:

ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x107d602b0> with a different variable scope than its first use.  First use of cell was with scope 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell', this attempt is with scope 'rnn/multi_rnn_cell/cell_1/basic_lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

**Comment by jrios6** [comment]
Facing same error here

**Comment by eHanseJoerg** [comment]
a solution has been posted by The_Mimi in the Udacity Forums: [https://discussions.udacity.com/t/dynamic-rnn-problem-with-tf-1-1/242634/8](url)

Basically, the syntax of MultiRNNCell has changed a bit. What you need to do now is unrolling the LSTM Cells in a for loop, and (important) instantiate the LSTM Cell in the same line.

It will not work if you do it on a different line.

So, this code will work: 
`    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.DropoutWrapper(
                                        tf.contrib.rnn.BasicLSTMCell(lstm_size), output_keep_prob = keep_prob) 
                                        for _ in range(num_layers)])`

**Comment by eHanseJoerg** [comment]
I have seen it was fixed it in a758200d7d99463e26ad7d7fccc88c52e7414faf . I think this issue may be closed then.
