### ISSUE TITLE
Any plan to make it comparable with tf 1.1 

### ISSUE THREAD

**Issue by johnsonice** [udacity/deep-learning#147]
many of us has been struggling to make the template code compatible with tf 1.1. In a lot of cases this is actually non-trivial. 

This issue has been raised multiple times in the forum and most of cases, we are asked to downgrade to tf 1.0. But that is not a reasonable solution to just ask people to stick to the older as everything else are evolving.

**Comment by mcleonard** [comment]
Yeah, I'm updating the code in places to make it compatible with 1.1 and 1.2. Mostly I'm using issues reported by students.
