### ISSUE TITLE
Typo in problem_unittests.py

### ISSUE THREAD

**Issue by damagode** [udacity/deep-learning#158]
Hi 👋 

I found a small typo in the `problem_unittests.py` file (https://github.com/udacity/deep-learning/blob/master/language-translation/problem_unittests.py#L89).

```
assert max_target_sequence_length.op.type == 'Max', \
            'Max Target Sequence Length is not a Placeholder.'
```

Instead of `== 'Max',` we might use `== 'Placeholder',`.

What do you think?

Thank you in advance

**Comment by extronics** [comment]
I think the test is right because `max_target_sequence_length` is supposed to be a `tf.reduce_max`, not `tf.placeholder`. But the description text could be `... is not a Max` instead of `... is not a Placeholder`.

**Comment by damagode** [comment]
Oh, I See, It makes a lot more sense now 😂 .
