### ISSUE TITLE
Why the projects aren't using python's type hint feature? 

### ISSUE THREAD

**Issue by zzdjk6** [udacity/deep-learning#17]
Since the python version we use is already equal or higher than 3.5, including type hint in projects code should enhance the IDE's auto-complete function and avoid lots of type errors while we writing code, as well as more clear indicating the requirement of every function we should write. 

Type hint feature refers: https://www.python.org/dev/peps/pep-0484/

**Comment by abhiojha8** [comment]
The workspace provided by Udacity in the classroom does not have type hints available. Students can however choose to do the projects locally in the IDE of their choice.
