### ISSUE TITLE
MultiRNNCell layer parameter should be defined with list comprehension

### ISSUE THREAD

**Issue by horvathj** [udacity/deep-learning#175]
I tried to define multiple layers of LSTMs in Project 4 according to these lines from Sentiment_RNN lesson.
# Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([drop] * lstm_layers)

this worked well in the lesson with Tensorflow 1.0

But in Tensorflow 1.1 warnes that this is not good! We should use this solution (linked in Project 4 notebook)
https://github.com/tensorflow/tensorflow/blob/6947f65a374ebf29e74bb71e36fd82760056d82c/tensorflow/docs_src/tutorials/recurrent.md#stacking-multiple-lstms

def lstm_cell():
  return tf.contrib.rnn.BasicLSTMCell(lstm_size)
stacked_lstm = tf.contrib.rnn.MultiRNNCell(
    [lstm_cell() for _ in range(number_of_layers)])

I think it would be great to mention this in the lessons notebook already.

**Comment by mcleonard** [comment]
Yeah, this is mentioned in the first RNN notebook

> But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like
> ```
> def build_cell(num_units, keep_prob):
>     lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
>     drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
> 
>     return drop
> 
> tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
> ```
