### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'TrainingHelper'

### ISSUE THREAD

**Issue by ankitPagalGuy** [udacity/deep-learning#179]
In project 4 , in Decoding - Training section , it's written 

Create a training decoding layer:
Create a tf.contrib.seq2seq.TrainingHelper
Create a tf.contrib.seq2seq.BasicDecoder
Obtain the decoder outputs from tf.contrib.seq2seq.dynamic_decode

but it is giving error  module 'tensorflow.contrib.seq2seq' has no attribute 'TrainingHelper' 

what should I do ?

**Comment by mcleonard** [comment]
Try updating your TensorFlow version to 1.2

**Comment by ankitPagalGuy** [comment]
Thanks
