### ISSUE TITLE
Incorrect codes in Translation Project

### ISSUE THREAD

**Issue by NELSONZHAO** [udacity/deep-learning#194]
There are some errors in function "get_batches".

```
def get_batches(targets, sources, batch_size, source_pad_int, target_pad_int):
    """Batch targets, sources, and the lengths of their sentences together"""
    for batch_i in range(0, len(sources)//batch_size):
        start_i = batch_i * batch_size
        sources_batch = sources[start_i:start_i + batch_size]
        targets_batch = targets[start_i:start_i + batch_size]
        pad_sources_batch = np.array(pad_sentence_batch(sources_batch, source_pad_int))
        pad_targets_batch = np.array(pad_sentence_batch(targets_batch, target_pad_int))
        
        # Need the lengths for the _lengths parameters
        pad_targets_lengths = []
        for target in pad_targets_batch:
            pad_targets_lengths.append(len(target))
        
        pad_source_lengths = []
        for source in pad_sources_batch:
            pad_source_lengths.append(len(source))
        
        yield pad_targets_batch, pad_sources_batch, pad_targets_lengths, pad_source_lengths
```

In the seq2seq loss function, we have pass weights into this function. These weights are not variables but masks. This mask gives the weightage to the input that has influence on the prediction i.e. how much influence, input has on the prediction.
For example:
[1,1,1,0,0] ----> [I love you <pad> <pad>]
[1,1,1,1,0] —> [it is very nice ]
[1,1,0,0,0] ----> [I am <pad> <pad> <pad>]
[1,1,1,1,1] -----> [She is a nice girl]
[1,1,1,0,0] ----> [I like you <pad> <pad>]

but in our code, we just loop the sentence that we have already pad, so that all the sentences in each batch have the same length. I think we should loop for “targets_batch”, not the “pad_targets_batch”.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
