### ISSUE TITLE
language-translation: tensorflow version higher then what's in anaconda 

### ISSUE THREAD

**Issue by stopachka** [udacity/deep-learning#210]
Hey team,

language translation requires tensorflow >= 1.1, however, the default install on the udacity machine-learning ami is 1.0.0 

To fix this, had to play around, and update tensorflow with anaconda. Would have been nice to have avoided having to do that xD

**Comment by abhiojha8** [comment]
The current code in many projects in this repo works only with TF=1.0.0. We may release a refresh with the latest packages at some point. Thanks for the feedback!
