### ISSUE TITLE
Get batches function is returning the wrong sequence lengths

### ISSUE THREAD

**Issue by datawrestler** [udacity/deep-learning#212]
When we feed the sequence lengths to the encoder, decoder, and mask for loss calculation, the same sequence lengths for all rows in the batch are being used. I do not believe this is the desired behavior as it will impact our loss calculation. I believe the fix is in the get_batches function, which should be: 

`    def get_batches(targets, sources, batch_size, source_pad_int, target_pad_int):
    """Batch targets, sources, and the lengths of their sentences together"""
    for batch_i in range(0, len(sources)//batch_size):
        start_i = batch_i * batch_size
        sources_batch = sources[start_i:start_i + batch_size]
        targets_batch = targets[start_i:start_i + batch_size]
        sources_lengths = [len(src) for src in sources_batch]
        targets_lengths = [len(tgt) for tgt in targets_batch]
        pad_sources_batch = np.array(pad_sentence_batch(sources_batch, source_pad_int))
        pad_targets_batch = np.array(pad_sentence_batch(targets_batch, target_pad_int))
        yield pad_targets_batch, pad_sources_batch, targets_lengths, sources_lengths`

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
