### ISSUE TITLE
Project-3 - test_build_nn fails with Tensorflow 1.3

### ISSUE THREAD

**Issue by acbellini** [udacity/deep-learning#216]
Using TF 1.3, the test_build_nn() test fails as the second dimension is not None. The same code on TF 1.1 works fine. Not showing the code as it's an assigment project.

```AssertionError: Final state wrong shape.  Found shape (2, 2, 128, 256)```

**Comment by lnlwd** [comment]
i lost like 5 minutes reviewing my code trying to find something wrong. thanks for the solution :smile:

**Comment by Mazeye** [comment]
Thanks, but how to complete this project in TF1.3?Or it only can be complete in TF1.1?

**Comment by lnlwd** [comment]
Hey @Mazeye I just changed my conda environment to tensorflow 1.1, just to complete the project.

**Comment by Mazeye** [comment]
@lnlwd OK,I know that, Thanks for your help,It really confused me.

**Comment by mimoralea** [comment]
Thanks!! Hopefully, this gets updated soon.
I had to install `cudatoolkit: 8.0-3 anaconda` in addition to the reqs.

**Comment by kkalera** [comment]
Had the same issue. For anyone looking how to install tensorflow gpu 1.1 on windows, run the following command:
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.1.0-cp35-cp35m-win_amd64.whl`

**Comment by hjwk** [comment]
No reaction from Udacity ?

**Comment by kkalera** [comment]
@hjwk doesn't look like it. Pretty sad tbh

**Comment by whusym** [comment]
If we comment out the unittest function, does the whole network still run fine? TF 1.4 user here.

**Comment by xizhenke** [comment]
Then could anyone please give an easy solution??

**Comment by xizhenke** [comment]
can anyone help?? this problem is not solved. what if some students cannot use TF 1.1.0? Please

**Comment by whusym** [comment]
I think you can go to the unittest file to modify the expected output. But overall it should not affect the program itself. For me, the only additional thing I have also changed for TF 1.4 is to change 
`pred_word = pick_word(probabilities[dyn_seq_length-1], int_to_vocab)` 
into 
`pred_word = pick_word(probabilities[0][dyn_seq_length-1], int_to_vocab)`
in the **Generate TV Script** block in the end.

Hope this helps!

**Comment by kkalera** [comment]
@xizhenke why wouldn't you be able to use tensorflow 1.1 for the project?

**Comment by xizhenke** [comment]
@whusym 
Thank you for your detailed answer! I really appreciate it!
@kkalera 
Thank you for the suggestion. When we encounter problems, going backward is not the ultimate solution.

**Comment by acbellini** [comment]
If you change the unit test, it will pass for you, but then it will not pass udacity's testing. So, you may just want to use TF 1.1...

**Comment by Raynier-XFintell** [comment]
Hi all, just to keep the thread going. I have build a tensorflow 1.5 env with GPU on a new surface book 2... same issue failing at same the point...

Is there a way forward yet that gets sound this issue? 

You'd think that UDACITY collects enough money from us to at least regression test their projects on new tensorflow versions...

**Comment by kkalera** [comment]
@Raynier-XFintell, I share your frustration. I've encountered a few problems so far and they don't respond to any of the github issues.

**Comment by david-wb** [comment]
Here is a solution that worked for me using the AWS deep learning ami. 

1. Add jupyter kernel for your conda environment:
```
python -m ipykernel install --user --name yourenv --display-name "Python (yourenv)"
```
2. Replace the line `tensorflow==1.0.0` in requirements.txt with `tensorflow-gpu==1.0.0`. 
3. In your jupyter notebook switch kernels in the menu bar with `kernel->change kernel->Python (yourenv)`. 

Good luck!

**Comment by abhiojha8** [comment]
We are coming up with a refresh that will contain newer package versions. For now, the exercises work only with the versions provided, and newer versions are not supported.
