### ISSUE TITLE
First neural network has deprecated code

### ISSUE THREAD

**Issue by valivetiravichandra** [udacity/deep-learning#234]
https://github.com/udacity/deep-learning/tree/master/first-neural-network
In jupyter notebook, we have
  X, y = train_features.ix[batch].values, train_targets.ix[batch]['cnt']
instead of 
  X, y = train_features.loc[batch].values, train_targets.loc[batch]['cnt']
which breaks the code while submitting it to project assistant.
and even here we have ix:
dates = pd.to_datetime(rides.ix[test_data.index]['dteday'])
refer this:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

Warning Starting in 0.20.0, the .ix indexer is deprecated, in favor of the more strict .iloc and .loc indexers. 
.ix offers a lot of magic on the inference of what the user wants to do. To wit, .ix can decide to index positionally OR via labels depending on the data type of the index. This has caused quite a bit of user confusion over the years.
The recommended methods of indexing are:
.loc if you want to label index
.iloc if you want to positionally index.

**Comment by maksbd19** [comment]
This issue is still there and it is making the project too much hard for me to complete. This is highly unexpected from the people and I am astonished to see this is not yet taken care of!

**Comment by abhiojha8** [comment]
This has been resolved.
