### ISSUE TITLE
Project 5 - Face generation (matplotlib version issue)

### ISSUE THREAD

**Issue by NekuSakuraba** [udacity/deep-learning#235]
The following code doesn't work with `matplotlib` version `2.1.0`.
I had to downgrade it to `2.0.2` version.
```
mnist_images = helper.get_batch(glob(os.path.join(data_dir, 'mnist/*.jpg'))[:show_n_images], 28, 28, 'L')
pyplot.imshow(helper.images_square_grid(mnist_images, 'L'), cmap='gray')
```

**Comment by kkalera** [comment]
Same issue here, for anyone looking how to downgrade, run the following command if you're using anaconda:

conda install matplotlib=2.0.0

Again, sad to see no response from udacity. Not the first issue without response I encounter.

**Comment by thak123** [comment]
Why is the code not working with latest matplotlib ?

**Comment by OzgunBu** [comment]
I used this for now, just a hack, though :(

mnist_images = helper.get_batch(glob(os.path.join(data_dir, 'mnist/*.jpg'))[:show_n_images], 28, 28, 'RGB')
pyplot.imshow(helper.images_square_grid(mnist_images, 'RGB'))

**Comment by abhiojha8** [comment]
The code currently works only on the versions mentioned in the requirements.txt or the ones provided with the .yml file. I understand that some of them are now deprecated. We are working on updating the code and requirements to match the latest versions.
