### ISSUE TITLE
Missing %matplotlib inline

### ISSUE THREAD

**Issue by varung** [udacity/deep-learning#237]
In the workspace for: https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/bb1f6b73-b886-4ed5-ba63-a992faf7d873

(int the notebook StudentAdmissionsKeras.ipynb)

**Comment by abhiojha8** [comment]
added `%matplotlib inline`.
