### ISSUE TITLE
Minor typo in weight_initialization.ipynb

### ISSUE THREAD

**Issue by sbbogdan** [udacity/deep-learning#246]
Section: General rule for setting weights. 

Current copy: "The general rule for setting the weights in a neural network is to be close to zero without being too small. A good pracitce is to start your weights in the range..."

Issue: 'pracitce' --> practice. 

![image](https://user-images.githubusercontent.com/34140431/35248595-97b01072-ff83-11e7-925f-6c49562c509f.png)

**Comment by sbbogdan** [comment]
Another minor typo immediately above 'Truncated Normal Distribution' section.

"The normal distribution gave a slight increasse in accuracy and loss."

'increasse' --> 'increase'

![image](https://user-images.githubusercontent.com/34140431/35249793-47f13a20-ff88-11e7-9f37-8a2e67d98c6b.png)

**Comment by abhiojha8** [comment]
Fixed the typos.
