### ISSUE TITLE
"Anna_KaRNNa.ipynb": Transferring state between epochs - possible error

### ISSUE THREAD

**Issue by ivanbgd** [udacity/deep-learning#247]
Hey guys!
This is about the training section in the "Anna_KaRNNa.ipynb".
The way it seems to me is that we are passing `final_state` of a batch as `initial_state` to the next batch in the same epoch. We get `new_state`, and populate `model.initial_state` in the feed dictionary with it, for the next batch.
Somebody please correct me if I'm wrong.
But the code provided, as it seems to me, doesn't transfer the state of the very last batch in an epoch on to the first batch in the next epoch. The way I see it, it transfers the state from the batch that is previous to the very last one, to the first batch of a new epoch.
So, shouldn't we update `model.initial_state` with `new_state` at the end of each epoch, to fill `model.initial_state` with the `final_state` of the very last batch? And how should we do it? Can we just type: `model.initial_state = new_state`?
Or, maybe we should simply omit `new_state = sess.run(model.initial_state)` at the beginning of each epoch, because it uses state from the batch previous to the last one? Then, we could just move that line before the loop over epochs, to assign all zeros to `new_state`. The code overwrites `new_state` at the beginning of each epoch, with the value from two batches before, where it should keep the lastly assigned value, which is from the one batch before (the very last batch), and which it had already got. I think this overwrite is the error.
Just to be sure: All zeros for `initial_state` are achieved in the constructor, and used only once. Later on, we just transfer the state, which is non-zero after the very beginning of the training. Right?
Please correct me if I got something wrong.

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you!
