### ISSUE TITLE
RegressionSolutions.ipynb

### ISSUE THREAD

**Issue by leesper** [udacity/deep-learning#253]
Can anybody tells me why in [RegressionSolutions](https://github.com/udacity/deep-learning/blob/master/linear-regression/RegressionSolutions.ipynb), when we update the slope m it is `m += m*diff*learning_rate` instead of `m += x[i]*diff*learning_rate`, I think the latter is consistent with the video about square trick:

![1985729060](https://user-images.githubusercontent.com/5260728/36404925-980c16d6-1628-11e8-8768-afba411b1d30.jpg)

so is it a bug or sth ? Thank you

**Comment by leesper** [comment]
@luisguiserrano

**Comment by DreamXiaoHai** [comment]
@leesper . I have the same problem. If you had the answer, please tell me . thanks

**Comment by KingofCatfish** [comment]
Agree.

**Comment by abhiojha8** [comment]
We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. Thanks.
