### ISSUE TITLE
Intro to Tensorflow Lab: Tensorflow version not importing

### ISSUE THREAD

**Issue by Rendiere** [udacity/deep-learning#259]
Installing the `dlnd-tf-lab` virtual env using the environment.yaml causes an issue with importing tensorflow.

Running this cell, with everything "out of the box":

```python
%matplotlib inline

# Load the modules
import pickle
import math

import numpy as np
import tensorflow as tf
from tqdm import tqdm
import matplotlib.pyplot as plt

# Reload the data
pickle_file = 'notMNIST.pickle'
with open(pickle_file, 'rb') as f:
    pickle_data = pickle.load(f)
    train_features = pickle_data['train_dataset']
    train_labels = pickle_data['train_labels']
    valid_features = pickle_data['valid_dataset']
    valid_labels = pickle_data['valid_labels']
    test_features = pickle_data['test_dataset']
    test_labels = pickle_data['test_labels']
    del pickle_data  # Free up memory

print('Data and modules loaded.')
```

Causes an issue: `TypeError: __init__() got an unexpected keyword argument 'file'`

I've fixed this issue by changing the tensorflow version from `tensorflow>=0.12` to `tensorflow==0.12`.

I will be making a PR for this to be changed. 

(Not sure what the flow is, but making this issue so that if people search for this error they will at least find my solution)

**Comment by abhiojha8** [comment]
Merged the PR to fix this.
