### ISSUE TITLE
Wording in embeddings exercise

### ISSUE THREAD

**Issue by AlphaGit** [udacity/deep-learning#26]
I believe the current wording in the embeddings (word2vec) exercise can be changed to avoid confusions.

`embeddings/Skip-Gram%20word2vec.ipynb` says ("Building the graph" cell):

> We can discard the softmax layer becuase we don't really care about making predictions with this network.

Later on, in the "Negative Sampling" cell:

> For every example we give the network, we train it using the output from the softmax layer.

**Comment by mcleonard** [comment]
Yeah, the first sentence should be "After training, we can discard ..."

**Comment by abhiojha8** [comment]
Thanks! We have updated the notebook.
