### ISSUE TITLE
Conda env issue

### ISSUE THREAD

**Issue by init27** [udacity/deep-learning#270]
Setting up Conda (Linux_GPU.yml) gives the error
```
ResolvePackageNotFound: 
  - pyzmq==16.0.2=py35_1
```

**Comment by abhiojha8** [comment]
Can you provide us additional information to investigate the issue? 
Which environment are you trying to setup?
Which `Linux_GPU.yml` file are you using?

**Comment by abhiojha8** [comment]
Closing this issue for now. We are going to add a new `requirements.txt` file for this ND. Thanks :)
