### ISSUE TITLE
`get_dummies` function in numpy ?  (StudentAdmissions.ipynb)

### ISSUE THREAD

**Issue by imkeno** [udacity/deep-learning#271]
## TODO: One-hot encoding the rank
Use the `get_dummies` function in numpy in order to one-hot encode the data.

I don't find get_dummies in numpy,I only find it in pandas

**Comment by gggauravgandhi** [comment]
Numpy doesn't have that function, you have to use Pandas for it. 
`pandas.get_dummies `

**Comment by anuraagrijal3138** [comment]
In pandas.get_dummies, dtype attribute does not work. Please help!

pd.get_dummies(pd.Series(list('abc')), dtype=float)
TypeError: get_dummies() got an unexpected keyword argument 'dtype'

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks
