### ISSUE TITLE
dlnd_face_generation.ipynb MNIST explore Data cell doesn't seem to work with one color channel

### ISSUE THREAD

**Issue by Olu93** [udacity/deep-learning#272]
The following code within the Notebook leads to an error if used with L as color scale.
`mnist_images = helper.get_batch(glob(os.path.join(data_dir, 'mnist/*.jpg'))[:show_n_images], 28, 28, 'RGB')
pyplot.imshow(helper.images_square_grid(mnist_images, 'RGB'), cmap='gray')`

Error is following:
`<matplotlib.image.AxesImage at 0xd90c69bcf8>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\conda\conda\envs\tf\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    330                 pass
    331             else:
--> 332                 return printer(obj)
    333             # Finally look for special method names
    334             method = get_real_method(obj, self.print_method)

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    235 
    236     if 'png' in formats:
--> 237         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    238     if 'retina' in formats or 'png2x' in formats:
    239         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    119 
    120     bytes_io = BytesIO()
--> 121     fig.canvas.print_figure(bytes_io, **kw)
    122     data = bytes_io.getvalue()
    123     if fmt == 'svg':

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2214                     orientation=orientation,
   2215                     dryrun=True,
-> 2216                     **kwargs)
   2217                 renderer = self.figure._cachedRenderer
   2218                 bbox_inches = self.figure.get_tightbbox(renderer)

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    505 
    506     def print_png(self, filename_or_obj, *args, **kwargs):
--> 507         FigureCanvasAgg.draw(self)
    508         renderer = self.get_renderer()
    509         original_dpi = renderer.dpi

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    428             # if toolbar:
    429             #     toolbar.set_cursor(cursors.WAIT)
--> 430             self.figure.draw(self.renderer)
    431         finally:
    432             # if toolbar:

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1297 
   1298             mimage._draw_list_compositing_images(
-> 1299                 renderer, self, artists, self.suppressComposite)
   1300 
   1301             renderer.close_group('figure')

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2435             renderer.stop_rasterizing()
   2436 
-> 2437         mimage._draw_list_compositing_images(renderer, self, artists)
   2438 
   2439         renderer.close_group('axes')

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\image.py in draw(self, renderer, *args, **kwargs)
    564         else:
    565             im, l, b, trans = self.make_image(
--> 566                 renderer, renderer.get_image_magnification())
    567             if im is not None:
    568                 renderer.draw_image(gc, l, b, im)

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\image.py in make_image(self, renderer, magnification, unsampled)
    791         return self._make_image(
    792             self._A, bbox, transformed_bbox, self.axes.bbox, magnification,
--> 793             unsampled=unsampled)
    794 
    795     def _check_unsampled_image(self, renderer):

~\AppData\Local\conda\conda\envs\tf\lib\site-packages\matplotlib\image.py in _make_image(self, A, in_bbox, out_bbox, clip_bbox, magnification, unsampled, round_to_pixel_border)
    428 
    429                 mask = np.empty(A.shape, dtype=np.float32)
--> 430                 if A.mask.shape == A.shape:
    431                     # this is the case of a nontrivial mask
    432                     mask[:] = np.where(A.mask, np.float32(np.nan),

AttributeError: 'numpy.ndarray' object has no attribute 'mask'

<matplotlib.figure.Figure at 0xd96ff9bf98>`

If I change it to following code it works fine:
`mnist_images = helper.get_batch(glob(os.path.join(data_dir, 'mnist/*.jpg'))[:show_n_images], 28, 28, 'RGB')
pyplot.imshow(helper.images_square_grid(mnist_images, 'RGB'), cmap='gray')`

Following are my packages in my Python 3 environment:
absl-py==0.2.1
alabaster==0.7.10
astor==0.6.2
astroid==1.5.3
Babel==2.5.0
bleach==1.5.0
certifi==2016.2.28
chardet==3.0.4
cloudpickle==0.5.3
colorama==0.3.9
cycler==0.10.0
dask==0.17.5
decorator==4.1.2
docutils==0.14
entrypoints==0.2.3
gast==0.2.0
grpcio==1.12.0
html5lib==0.9999999
imagesize==0.7.1
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.15
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
lazy-object-proxy==1.3.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.4.0
networkx==2.1
notebook==5.0.0
numpy==1.14.3
numpydoc==0.7.0
pandocfilters==1.4.2
path.py==10.3.1
pickleshare==0.7.4
Pillow==5.1.0
prompt-toolkit==1.0.15
protobuf==3.5.2.post1
psutil==5.2.2
pycodestyle==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.2
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.14.2
rope-py3k==0.9.4.post1
scikit-image==0.14.0
scikit-learn==0.19.1
scipy==1.1.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
snowballstemmer==1.2.1
sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
tensorboard==1.8.0
tensorflow-gpu==1.8.0
termcolor==1.1.0
testpath==0.3
toolz==0.9.0
tornado==4.5.2
tqdm==4.23.4
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
widgetsnbextension==3.0.2
wincertstore==0.2
wrapt==1.10.11

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
