### ISSUE TITLE
Weight Issue in sentiment-network/Sentiment_Classification_Solutions.ipynb

### ISSUE THREAD

**Issue by yingding** [udacity/deep-learning#276]
In Cell [32] Project 3 of file sentiment-network/Sentiment_Classification_Solutions.ipynb

Within the method **init_network**
```python
        # These are the weights between the hidden layer and the output layer.
        self.weights_1_2 = np.random.normal(0.0, self.output_nodes**-0.5, 
                                                (self.hidden_nodes, self.output_nodes))
```

Is this a typo "self.output_nodes**-0.5"? Since the cardinality of output_nodes is always 1.
Maybe it is intended to use "self.hidden_nodes**-0.5", since the hidden_nodes are the input of weights_1_2. 

With the following weights, the FNN learns something already at the beginning.
```python
        # These are the weights between the hidden layer and the output layer.
        self.weights_1_2 = np.random.normal(0.0, self.hidden_nodes**-0.5, 
                                                (self.hidden_nodes, self.output_nodes))
```

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you
