### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 84: invalid continuation byte

### ISSUE THREAD

**Issue by gurupetach** [udacity/deep-learning#287]
how can i solve this.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 84: invalid continuation byte

**Comment by abhiojha8** [comment]
@gurupetach To help us resolve this issue please tell us which code file were you running? Also, add the error stack trace.

**Comment by gurupetach** [comment]
managed to solve
