### ISSUE TITLE
Embeddings question

### ISSUE THREAD

**Issue by jperl** [udacity/deep-learning#32]
In the [embeddings](https://github.com/udacity/deep-learning/blob/master/embeddings/Skip-Grams-Solution.ipynb) `get_batches` function there is this line

```python
# only full batches
words = words[:n_batches*batch_size]
```

`n_batches` is the length of `words` so it seems this extends words to be 1000x it's size.

What is this trying to do?

**Comment by Brok-Bucholtz** [comment]
`n_batches` is `len(words)//batch_size`, the number of full batches that can be taken from `words`.
`words[:n_batches*batch_size]` is slicing up to all the words that will be used for the batches.

**Comment by jperl** [comment]
Sorry python newbie. When I asked this question I thought `//` were comments :).
