### ISSUE TITLE
None element causes tf.clip_by_value operation error.

### ISSUE THREAD

**Issue by Michael-Jing** [udacity/deep-learning#43]
In dlnd_tv_script_generation.ipynb, I have to change 
    `capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients]`
to
   `capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients if grad is not None]`
to get the code running, since one of the grad value is None.

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know.  We fixed this in PR https://github.com/udacity/deep-learning/pull/102
