### ISSUE TITLE
minor mistake in sentiment-rnn solution.ipynb

### ISSUE THREAD

**Issue by jychstar** [udacity/deep-learning#48]
In the data preprocessing, the solution used open(), read(), join(), split(), to get the reviews and labels. The problem is that it creates an empty review and label as the last row.  Although `reviews_ints = [each for each in reviews_ints if len(each) > 0]` Filter out that review with 0 length, but `features = np.zeros((len(reviews), seq_len), dtype=int)` and subsequent iteration put the empty one back as the last forgotten row. Luckily, it is the last one. So it only causes an error of 0.04% for the testing accuracy. 

The origin of this mistake is due to `split('\n')`.  So keep in mind to manually remove the last element.

Alternatively, csv module does the job worry-free. 
```python
from string import punctuation
import csv
reviews = []
words =[]
with open('reviews.txt') as f:
    rows = csv.reader(f)
    for row in rows:
        text = ''.join([char for char in str(row) if char not in punctuation])
        words.extend(text.split())
        reviews.append(text)
```

**Comment by christiankaiser** [comment]
Additionally, if one review is removed, it also needs to be removed from the labels, which has been forgotten.

To fix the problem with minor changes, it's enough to just add `.strip()` after the two `f.read()` in the beginning:

```python
with open('../sentiment_network/reviews.txt', 'r') as f:
    reviews = f.read().strip()
with open('../sentiment_network/labels.txt', 'r') as f:
    labels = f.read().strip()
```
