### ISSUE TITLE
Sentiment RNN Solution.ipynb: saver.restore(...('/output/checkpoints')) not restoring

### ISSUE THREAD

**Issue by navyg8r** [udacity/deep-learning#51]
The "Testing" Block (Last block) does not seem to restore correctly:
    saver.restore(sess, tf.train.latest_checkpoint('/output/checkpoints'))

Probably because the Training Block (previous block) saves training data like this:
    saver.save(sess, "checkpoints/sentiment.ckpt")

I changed the Testing block to the following and it appears to work:
    saver.restore(sess, tf.train.latest_checkpoint('checkpoints'))

**Comment by mcleonard** [comment]
The path for the checkpoint files has been updated
