### ISSUE TITLE
Sentiment RNN Embedding Size

### ISSUE THREAD

**Issue by mkowoods** [udacity/deep-learning#57]
For the embedding you're using a shape = (n_words, embed_size). But in the preprocessing step we shift the indices of all the words by 1 and leave index 0 as the "null" word for padding. so wouldnt we need the shape to be (n_words + 1, embed_size).

in a toy example if we had a 10 word vocabulary we would need an 11 row embed matrix (with the 0th row serving as the "null" word). And all of the other words would be indexed 1 - 10.

**Comment by johnsonice** [comment]
@mkowoods  I think you are right, just confirmed this with Forum mentor. they should fix this.
