### ISSUE TITLE
error in Sentiment Classification Projects.ipynb

### ISSUE THREAD

**Issue by CtheSky** [udacity/deep-learning#66]
Hi, I'm working on [Sentiment_Classification_Projects.ipynb](https://github.com/udacity/deep-learning/blob/master/sentiment-network/Sentiment_Classification_Projects.ipynb). 
  
And I am confused with following code at the end of project 3:
`mlp = SentimentNetwork(reviews[:-1000],labels[:-1000], learning_rate=0.1)`
  
It will preprocess the given reviews to fill `word2index`  which is a dict, but when I execute next line:
`mlp.test(reviews[-1000:],labels[-1000:])`
It throws `KeyError: 'reprogram'`. 

It seems that there are some words only existing in last 1000 reviews, and I think first line should be:
`mlp = SentimentNetwork(reviews, labels, learning_rate=0.1)`

I'm not sure about it, did I miss something?

**Comment by nghiattran** [comment]
That error happens because a test review contains a word that is not in training reviews so that word is not saved into `word2index` set. You can ignore those unknown words by not setting input vector whenever these words are encountered.

**Comment by LivingProgram** [comment]
This should probably be fixed in the programming instructions or else it makes it really confusing to debug

**Comment by LivingProgram** [comment]
For future reference something like this will work : 

```python
for word in review.split(' '):
    try:
        self.layer_0[0,self.word2index[word]] += 1
    except:
        pass
```

**Comment by CihanSoylu** [comment]
The following worked for me

```python
indices = set()
for word in review.split(' '):
    if word in self.word2index.keys():
        indices.add(self.word2index[word])
```

**Comment by abhiojha8** [comment]
We will make appropriate changes in the refresh. Thanks :)
