### ISSUE TITLE
Missing section in language translation project's notebook?

### ISSUE THREAD

**Issue by kulshekhar** [udacity/deep-learning#74]
In the 'Build the Neural Network > Build the Neural Network' section, the instructions are to use `process_encoding_input` to process the target data. At the beginning of the `Build the Neural Network` section, this function is also listed as one of the functions we have to implement. The rubric also mentions this function.

I'm a bit confused - do the instructions need to be updated or is there a section (with instructions to build this function) for this missing?

fwiw, this section was present in an earlier version of the notebook

**Comment by Brok-Bucholtz** [comment]
The function name was renamed, however those two places didn't get changed.  It's fixed now:
https://github.com/udacity/deep-learning/pull/76

Thanks for letting us know.
