### ISSUE TITLE
No content in 'gym' subfolder in 'reinforcements'. Pip install in lesson fails

### ISSUE THREAD

**Issue by pinemind** [udacity/deep-learning#75]
Hi,

The updated repo for the release of new content (mainly Reinforcement Learning lessons) has an empty 'gym' directory. For the lesson, we need to install OpenAI which is supposed to be contained in that directory. Therefore, pip install -e . fails since there is no script in this directory.

**Comment by mcleonard** [comment]
This is because `gym` is a submodule. Need to do `git submodule --init --recursive` first. I updated the instructions in the classroom.
