### ISSUE TITLE
tv script generation embed_dim not defined

### ISSUE THREAD

**Issue by acautin** [udacity/deep-learning#79]
after this change https://github.com/udacity/deep-learning/commit/b5d76add108d5a8d96ccfb2ab07b68b878fd1a15#diff-d449397f895434a819eb879dd0ca8f5cR639

It is not possible to execute the cell anymore as the variable embed_dim is not defined.

**Comment by Brok-Bucholtz** [comment]
@acautin,

The variable `embed_dim` is defined as `None` in the previous cell.  Just like all the hyperparameters, it's part of the project to replace `None` with your own value.

**Comment by acautin** [comment]
Oh thanks for the quick reply, was working with the previous version, didn't notice.
