### ISSUE TITLE
In dlnd_languate_translation.ipynb 

### ISSUE THREAD

**Issue by yuntai** [udacity/deep-learning#83]
In 'build the graph',
`max_target_sentence_length = max([len(sentence) for sentence in source_int_text])`
is meant to be
` .. for sentence in target_int_text])`?

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know.  We change the variable name to match the content: https://github.com/udacity/deep-learning/pull/90

**Comment by yuntai** [comment]
in aead76e5f26f5d5848133d3ee44770442c7259c4
```
-    "max_target_sentence_length = max([len(sentence) for sentence in source_int_text])\n",
+    "max_source_sentence_length = max([len(sentence) for sentence in source_int_text])\n",
```

why do we use `max_source_sentence_length` instead of `max_target_sentence_length`
since the cost is calculated with seq2seq of target sequence, wouldn't it be that `max_target_sentence_length` will give better cost value? so the fix should be
`max_target_sentence_length = max([len(sentence) for sentence in target_int_text])\n`
