### ISSUE TITLE
Project 4 vagueness of GO ID

### ISSUE THREAD

**Issue by DecentGradient** [udacity/deep-learning#95]
in the process decoding input section  ".... each batch in target_data and concat the GO ID to the ..." perhaps GO should be replaced  with <GO>

**Comment by abhiojha8** [comment]
Though we are a little late to respond, we suggest you add a PR for this if possible. Thanks :)

**Comment by DecentGradient** [comment]
While I do applaud you for your diligence in clearing old issues, I don't think that I'm in the best position to create a PR for this issue anymore.
